-include /opt/build-harness/Makefile.prow

.PHONY: copyright-check
copyright-check:
	./copyright-check.sh $(TRAVIS_BRANCH)

lint:
	npm run lint

install:
	npm ci

.PHONY: build
build:
	npm run build:production

.PHONY: unit-tests
unit-tests:
	if [ ! -d "test-output" ]; then \
		mkdir test-output; \
	fi
	npm test