-include /opt/build-harness/Makefile.prow

.PHONY: build
build:
	npm run build:production

lint:
	npm run lint

install:
	npm ci

.PHONY: unit-tests
unit-tests:
	if [ ! -d "test-output" ]; then \
		mkdir test-output; \
	fi
	npm test